{% set name = "getCalspec" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/getCalspec-{{ version }}.tar.gz
  sha256: a12ffd0f6c6a95ed40de016e5749ea7d0566f902cfbb07f148a173b94d82f885

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - astropy
    - astroquery
    - lxml
    - matplotlib-base >3.1
    - numpy >1.15
    - pandas
    - python >=3.7
    - scipy

test:
  imports:
    - getCalspec
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/LSSTDESC/getCalspec
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Package for getting calSpec spectra for stars by name

extra:
  recipe-maintainers:
    - jeremyneveu
    - mfisherlevine
