{% set name = "getCalspec" %}
{% set version = "2.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: d94aa6af084b6a4368c74be833212a7859355949fb8988d356ce06e4fa1591b3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - astropy
    - astroquery
    - lxml
    - matplotlib-base >3.1
    - numpy >1.15
    - pandas
    - python >={{ python_min }}
    - scipy

test:
  imports:
    - getCalspec
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/LSSTDESC/getCalspec
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Package for getting calSpec spectra for stars by name

extra:
  recipe-maintainers:
    - jeremyneveu
    - mfisherlevine
