{% set name = "getCalspec" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/getCalspec-{{ version }}.tar.gz
  sha256: fa45ba4979bec4fa1fe46266bd678ed4c981b5d7543979a62471a2595b822bff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - astropy
    - astroquery
    - lxml
    - matplotlib-base >3.1
    - numpy >1.15
    - pandas
    - python >={{ python_min }}
    - scipy

test:
  imports:
    - getCalspec
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/LSSTDESC/getCalspec
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Package for getting calSpec spectra for stars by name

extra:
  recipe-maintainers:
    - jeremyneveu
    - mfisherlevine
